### ISSUE TITLE
Добавить элемент label для чекбоксов и радиокнопок

### ISSUE THREAD

**Issue by Pegalet** [plechev-64/recall#2]
Чекбоксы (`<input type="checkbox">`) и радиокнопки (`<input type="radio">`) в профиле пользователя генерируются без элемента `<label>`. Поэтому нельзя выбрать чекбокс/радиокнопку щелкнув по их названи, что не очень хорошо в плане accessibility.

**Comment by plechev-64** [comment]
добавил в todo
