### ISSUE TITLE
Неправильно генерируется поле выбора даты

### ISSUE THREAD

**Issue by Pegalet** [plechev-64/recall#3]
Поле выбора даты в профиле пользователя генерируется как `<input type="text">`, а должно быть `<input type="date">`

**Comment by plechev-64** [comment]
Все правильно, это сделано специально, чтобы действие скрипта datepicker правильно работало и в браузерах с поддержкой HTML5, иначе при фокусе появляется два календаря от браузера и от скрипта datepicker.

**Comment by Pegalet** [comment]
Как альтернативный вариант, можно использовать Modernizr для определения того, поддерживает ли браузер `<input type="date">` или нет.

**Comment by plechev-64** [comment]
Можно, но не думаю, что подключение данного комбайна будет оправданным в данном случае
